### ISSUE TITLE
!botrole breaks when joining a new server

### ISSUE THREAD

**Issue by lizardman301** [lizardman301/Lizard-bot-rsf#114]
**Describe the bug**
!botrole will break the bot because it can not return a NoneType.

**To Reproduce**
1. Let Lizard-BOT join a new server
2. Use !botrole command
3. See error message

**Expected behavior**
!botrole should either return "No role" or "Everyone"

**Screenshots**
I am an idiot and deleted the message, but it occured in Mr_Madgear tourney's server.
![image](https://user-images.githubusercontent.com/56323690/116330567-a6be2b80-a782-11eb-8725-eed761c43d5f.png)

**Additional context**
I broke it 😢

**Comment by nogarremi** [comment]
I'll test this in a moment

**Comment by nogarremi** [comment]
Two issues in one.

First is there is a problem bringing in the empty disabled list on server start that makes the command fail (This should probably be affecting more commands)

Secondly, there is the fact that the empty botrole returns a None object 

Solution should be either a better default value in the database or telling python that if it is a None object to use an empty string or list instead.

I'll test the database one first since that is a better structural change and I would prefer it
